In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import os
import time
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
import json
from glob import glob
from PIL import Image
import pickle
import random

In [3]:
### data

!wget https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_Dataset.zip

!wget https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_text.zip


import zipfile

def unzip_data(filename):
  """
  Unzips filename into the current working directory.

  Args:
    filename (str): a filepath to a target zip folder to be unzipped.
  """
  zip_ref = zipfile.ZipFile(filename, "r")
  zip_ref.extractall()
  zip_ref.close()


unzip_data("/content/Flickr8k_Dataset.zip")
unzip_data("/content/Flickr8k_text.zip")

--2023-11-24 12:41:36--  https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_Dataset.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/124585957/47f52b80-3501-11e9-8f49-4515a2a3339b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231124%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231124T124136Z&X-Amz-Expires=300&X-Amz-Signature=d860cd25285b26e82c004ff95f3bb374ac9cf3dc8da9c2ba27583eae6f47f007&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=124585957&response-content-disposition=attachment%3B%20filename%3DFlickr8k_Dataset.zip&response-content-type=application%2Foctet-stream [following]
--2023-11-24 12:41:36--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/124585957/47f52b80-3501-11e9-8f49-4515a2a

In [4]:
image_path = "/content/Flicker8k_Dataset"
feat_path = "/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/image_feat"
text_path = "/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/captions.txt.zip"

In [5]:
df = pd.read_csv(text_path, skipinitialspace=True)
df.shape

(40455, 2)

In [6]:
8091*5

40455

In [7]:
### each image has 4 - 5 captions for training

In [8]:
image_name_list = list(set(df['image'])) #obtaining unique instance name of each image
image_path_list = list(map(lambda arg: image_path + "/" + arg, image_name_list))
feat_path_list = list(map(lambda arg: feat_path + arg, image_name_list))
#Its imp to keep images and features in different directories so as to avoid Colab's infamous I/O error

In [9]:
len(image_path_list)

8091

In [10]:
image_path_list[:3]

['/content/Flicker8k_Dataset/2248487950_c62d0c81a9.jpg',
 '/content/Flicker8k_Dataset/3126795109_73920ed5dc.jpg',
 '/content/Flicker8k_Dataset/3542484764_77d8920ec9.jpg']

In [11]:
feat_path_list[:5]

['/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/image_feat2248487950_c62d0c81a9.jpg',
 '/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/image_feat3126795109_73920ed5dc.jpg',
 '/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/image_feat3542484764_77d8920ec9.jpg',
 '/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/image_feat745563422_f4fa7d9157.jpg',
 '/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/image_feat2584020755_14e2b3e8fc.jpg']

In [12]:
def feat_extract():#Here we are performing surgery on a pretrained Inception V3 model so as to just obtain a model upto last conv layer

  IV3 = tf.keras.applications.InceptionV3(include_top=False,weights='imagenet') #creating an inceptionV3 instance without last classification layer

  x_in = IV3.input #we will feed input to the input layer of inception V3
  x_out= IV3.layers[-1].output #output of the last conv layer in inception V3 will will be taken as output

  return tf.keras.Model(inputs=x_in, outputs=x_out) #Output will be of dimention 8*8*2048

mod_fe = feat_extract()

87910968/87910968 [==============================] - 1s 0us/step


In [13]:
mod_fe.save('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/IV3_feat.h5') #saving because, we will also need it during evaluation


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


<!-- https://www.tensorflow.org/api_docs/python/tf/io/read_file

`@tf.function
def load_image(filename):
  raw = tf.io.read_file(filename)
  image = tf.image.decode_png(raw, channels=3)
  // the `print` executes during tracing.
  print("Initial shape: ", image.shape)
  image.set_shape([28, 28, 3])
  print("Final shape: ", image.shape)
  return image` -->

In [14]:
# @tf.function  from tensorflow
# def load_image(filename):
#   raw = tf.io.read_file(filename)
#   image = tf.image.decode_png(raw, channels=3)
#   # the `print` executes during tracing.
#   print("Initial shape: ", image.shape)
#   image.set_shape([28, 28, 3])
#   print("Final shape: ", image.shape)
#   return image

In [15]:
def load_image(arg):
    img = tf.io.read_file(arg)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (299, 299))
    img = tf.keras.applications.inception_v3.preprocess_input(img)
    return img, arg

In [16]:
load_image("/content/Flicker8k_Dataset/1000268201_693b08cb0e.jpg")

(<tf.Tensor: shape=(299, 299, 3), dtype=float32, numpy=
 array([[[-5.4579198e-01, -5.1085913e-01, -3.7435186e-01],
         [-1.4921635e-01, -1.9675493e-04, -3.1106710e-02],
         [-9.7177267e-02,  4.6858430e-02,  4.3021560e-02],
         ...,
         [-9.7224247e-01, -9.6819955e-01, -9.8191810e-01],
         [-9.6078575e-01, -9.4020623e-01, -9.7377020e-01],
         [-9.6212077e-01, -9.3846858e-01, -9.8195148e-01]],
 
        [[-5.7653260e-01, -5.3617233e-01, -4.2858374e-01],
         [-1.4806336e-01,  5.8089495e-03, -5.5708170e-02],
         [-7.8158259e-02,  6.0893416e-02,  7.8846335e-02],
         ...,
         [-9.6420521e-01, -9.5636207e-01, -9.8523390e-01],
         [-9.3927324e-01, -9.2645574e-01, -9.5595336e-01],
         [-9.9189347e-01, -9.6899247e-01, -9.7989315e-01]],
 
        [[-5.9273523e-01, -5.6866682e-01, -4.3528360e-01],
         [-1.3315433e-01,  5.4714680e-03, -1.3691187e-02],
         [-8.0161095e-02,  5.6944609e-02,  1.0495746e-01],
         ...,
         [-

In [17]:
load_image('/content/Flicker8k_Dataset/825918657_d92f1761f4.jpg')     # as we set image path

(<tf.Tensor: shape=(299, 299, 3), dtype=float32, numpy=
 array([[[-0.9823393 , -0.65909445, -0.66317093],
         [-0.9985265 , -0.6822833 , -0.6846297 ],
         [-0.9928995 , -0.64420986, -0.6681721 ],
         ...,
         [-0.984732  , -0.6269039 , -0.64259017],
         [-0.9995672 , -0.64447635, -0.6679404 ],
         [-0.9969739 , -0.5883913 , -0.6249709 ]],
 
        [[-0.99220705, -0.68260443, -0.7178329 ],
         [-0.9740813 , -0.6201478 , -0.6657902 ],
         [-0.99516666, -0.66863716, -0.70650196],
         ...,
         [-0.9970799 , -0.645727  , -0.66182804],
         [-0.98313266, -0.5912047 , -0.6146796 ],
         [-0.9360738 , -0.50957596, -0.5474541 ]],
 
        [[-0.9805548 , -0.64826286, -0.726326  ],
         [-0.9717946 , -0.6304666 , -0.7088867 ],
         [-0.9788602 , -0.6351131 , -0.71219355],
         ...,
         [-0.99568063, -0.63441914, -0.6526107 ],
         [-0.93981105, -0.5434094 , -0.5690849 ],
         [-0.89458907, -0.44414598, -0.4907329

In [18]:
image_path_list[:3] ##

['/content/Flicker8k_Dataset/2248487950_c62d0c81a9.jpg',
 '/content/Flicker8k_Dataset/3126795109_73920ed5dc.jpg',
 '/content/Flicker8k_Dataset/3542484764_77d8920ec9.jpg']

In [19]:


# image_dataset = tf.data.Dataset.from_tensor_slices(image_path_list)

# image_dataset = image_dataset.map(load_image, num_parallel_calls=tf.data.AUTOTUNE) #this is a map() extention for "Dataset" type stucture  (https://www.tensorflow.org/guide/data_performance)

# image_dataset = image_dataset.batch(32) #Since Inception V3 expects batch input anyways, so to leverage possible vectorization its better to send input in batches


In [20]:
#Features are being extracted seperately so as to avoid this part from becoming a bottleneck in further training
#Apart from this, features are cached in hard disk instead of RAM because of RAM's limitation in Collab
image_dataset = tf.data.Dataset.from_tensor_slices(image_path_list)
image_dataset = image_dataset.map(load_image, num_parallel_calls=tf.data.experimental.AUTOTUNE) #this is a map() extention for "Dataset" type stucture
image_dataset = image_dataset.batch(32) #Since Inception V3 expects batch input anyways, so to leverage possible vectorization its better to send input in batches

for img, path in image_dataset:
  batch_features = mod_fe(img)
  batch_features = tf.reshape(batch_features,(batch_features.shape[0], 8*8, batch_features.shape[3]))

  for bf, p in zip(batch_features, path):
    path_ = p.numpy().decode("utf-8") #p is needed to be decoded as string becuase it is originally obtained as numpy object
    path_ = feat_path + path_[len(image_path):] # path_[len(image_path):] extracts name of image which is then concatenated to feature path
    np.save(path_, bf.numpy()) #saves feature matrix with same name as that of image
    #Feature matrix is of dim 64x2048

In [22]:
#verifying quantity
import os, os.path
path = '/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/image_feat'
num_files = len([f for f in os.listdir(path)if os.path.isfile(os.path.join(path, f))])

num_files

8091