In [2]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import gensim
from gensim.models import Word2Vec
from gensim.models.phrases import Phrases, Phraser
import json
from nltk import RegexpTokenizer
import time
from keras.preprocessing.text import Tokenizer
import random
import multiprocessing
from nltk import RegexpTokenizer
import copy
import pickle
multiprocessing.cpu_count()


2

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Getting one with data

* Getting all required processors for training.

In [3]:
!wget https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_Dataset.zip

--2023-11-24 05:13:13--  https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_Dataset.zip
Resolving github.com (github.com)... 20.29.134.23
Connecting to github.com (github.com)|20.29.134.23|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/124585957/47f52b80-3501-11e9-8f49-4515a2a3339b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231124%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231124T051313Z&X-Amz-Expires=300&X-Amz-Signature=8d9f9438ca0a88542e8e27997b8e689fea510ad010008f8138589bdd5fe53aa8&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=124585957&response-content-disposition=attachment%3B%20filename%3DFlickr8k_Dataset.zip&response-content-type=application%2Foctet-stream [following]
--2023-11-24 05:13:13--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/124585957/47f52b80-3501-11e9-8f49-4515a2a

In [4]:
!wget https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_text.zip

--2023-11-24 05:13:18--  https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_text.zip
Resolving github.com (github.com)... 20.29.134.23
Connecting to github.com (github.com)|20.29.134.23|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/124585957/47f52b80-3501-11e9-8d2e-dd69a21a4362?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231124%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231124T051318Z&X-Amz-Expires=300&X-Amz-Signature=c5b109e55de9ef254bcffca604e60c752da355ac849881717befc8353cf689e3&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=124585957&response-content-disposition=attachment%3B%20filename%3DFlickr8k_text.zip&response-content-type=application%2Foctet-stream [following]
--2023-11-24 05:13:18--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/124585957/47f52b80-3501-11e9-8d2e-dd69a21a4362?

In [5]:
image_path = "/content/Flicker8k_Dataset"
text_path = "/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/captions.txt.zip"

In [6]:
import zipfile

def unzip_data(filename):
  """
  Unzips filename into the current working directory.

  Args:
    filename (str): a filepath to a target zip folder to be unzipped.
  """
  zip_ref = zipfile.ZipFile(filename, "r")
  zip_ref.extractall()
  zip_ref.close()

In [18]:
unzip_data("/content/Flickr8k_Dataset.zip")


In [19]:
unzip_data("/content/Flickr8k_text.zip")

In [9]:
df = pd.read_csv(text_path, skipinitialspace=True)
df.head()

image  \
0  1000268201_693b08cb0e.jpg   
1  1000268201_693b08cb0e.jpg   
2  1000268201_693b08cb0e.jpg   
3  1000268201_693b08cb0e.jpg   
4  1000268201_693b08cb0e.jpg   

                                             caption  
0  A child in a pink dress is climbing up a set o...  
1              A girl going into a wooden building .  
2   A little girl climbing into a wooden playhouse .  
3  A little girl climbing the stairs to her playh...  
4  A little girl in a pink dress going into a woo...

In [10]:
df['caption'] = df['caption'].apply(lambda arg: '<start> ' + str(arg) + ' <end>')

In [11]:
df.head()

image  \
0  1000268201_693b08cb0e.jpg   
1  1000268201_693b08cb0e.jpg   
2  1000268201_693b08cb0e.jpg   
3  1000268201_693b08cb0e.jpg   
4  1000268201_693b08cb0e.jpg   

                                             caption  
0  <start> A child in a pink dress is climbing up...  
1  <start> A girl going into a wooden building . ...  
2  <start> A little girl climbing into a wooden p...  
3  <start> A little girl climbing the stairs to h...  
4  <start> A little girl in a pink dress going in...

In [12]:
tokenizer = RegexpTokenizer(r'\w+|<start>|<end>') #tokenizing using only alphanumeric tokens and start, end tokens
df['tokens'] = df['caption'].apply(tokenizer.tokenize)

In [13]:
df.head()

image  \
0  1000268201_693b08cb0e.jpg   
1  1000268201_693b08cb0e.jpg   
2  1000268201_693b08cb0e.jpg   
3  1000268201_693b08cb0e.jpg   
4  1000268201_693b08cb0e.jpg   

                                             caption  \
0  <start> A child in a pink dress is climbing up...   
1  <start> A girl going into a wooden building . ...   
2  <start> A little girl climbing into a wooden p...   
3  <start> A little girl climbing the stairs to h...   
4  <start> A little girl in a pink dress going in...   

                                              tokens  
0  [<start>, A, child, in, a, pink, dress, is, cl...  
1  [<start>, A, girl, going, into, a, wooden, bui...  
2  [<start>, A, little, girl, climbing, into, a, ...  
3  [<start>, A, little, girl, climbing, the, stai...  
4  [<start>, A, little, girl, in, a, pink, dress,...

In [14]:
#Finding max length for padding
len_ = df['tokens'].apply(lambda arg: len(arg))
max_len = max(len_)
print(max_len)

39


In [15]:
#padding to max_len
def pad(arg):
  len_ = len(arg)
  len_ = max_len - len_
  lst = copy.deepcopy(arg)
  for i in np.arange(0,len_):
    lst.append('_')
  return lst

df['tokens_pad'] = df['tokens'].apply(pad)

In [16]:
df.loc[0]['tokens_pad']

['<start>',
 'A',
 'child',
 'in',
 'a',
 'pink',
 'dress',
 'is',
 'climbing',
 'up',
 'a',
 'set',
 'of',
 'stairs',
 'in',
 'an',
 'entry',
 'way',
 '<end>',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_']

In [26]:
#Training our custom word2vec model (its imp to do this because google's w2v lacks stopwords and <start>, <end> tokens)

%%time

obj_w2v=Word2Vec(sentences=df['tokens'], vector_size=300, min_count=1, window=2, sample = 6e-5, alpha= 0.03, workers=2, negative=20)


CPU times: user 6.13 s, sys: 60.5 ms, total: 6.19 s
Wall time: 5.03 s


In [27]:
# loading through api

# import gensim.downloader as api

# wv = api.load('word2vec-google-news-300')

In [28]:
word2vec_path = "/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/GoogleNews-vectors-negative300.bin.gz"

In [30]:
%%time
from gensim.models.word2vec import Word2Vec
from gensim.models import KeyedVectors

w2v_g = KeyedVectors.load_word2vec_format("/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/GoogleNews-vectors-negative300.bin.gz", binary=True)


CPU times: user 50.5 s, sys: 2.95 s, total: 53.4 s
Wall time: 56.6 s


In [33]:
words = list(w2v_g.index_to_key)
print(len(words)) , print(words[:10])

3000000
['</s>', 'in', 'for', 'that', 'is', 'on', '##', 'The', 'with', 'said']


(None, None)

In [34]:
#updating our local model's vocab with google's w2v's vocab
%%time
obj_w2v.build_vocab(words, update=True)


CPU times: user 7.79 s, sys: 39.6 ms, total: 7.83 s
Wall time: 7.98 s


In [ ]:
# obj_w2v.intersect_word2vec_format("/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/GoogleNews-vectors-negative300.bin.gz", lockf=1.0, binary=True)


#this function will look for words common in our vocab
#and in google's vocab and change the weight of such words to that in google's weight vector.
#Here we have set lockf=1 so that in further training weights of all the
#words are optimized

In [37]:
%%time

obj_w2v.train(df['tokens'], total_examples=len(df), epochs=obj_w2v.epochs) #we are training again so as to get weights adjusted
#This retraining is important so as to avoid clash of embedding space of google's w2v and our custom w2v

CPU times: user 3.87 s, sys: 41 ms, total: 3.91 s
Wall time: 2.2 s


(676297, 2592555)

In [49]:
 #This will save entire model

obj_w2v.save('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/w2v_imageCap.kv')

In [46]:
!pip install gensim

In [50]:
 # This will only save matrix / vocab of model

obj_w2v.wv.save_word2vec_format('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/w2v_imageCap.bin', binary=True)

In [51]:
from gensim.test.utils import datapath

word2vec = KeyedVectors.load_word2vec_format(datapath('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/w2v_imageCap.bin'), binary=True)

In [62]:
#Now we will create a new vocab of most used tokens and then later map them to their w2v embeddings
vec=Tokenizer()
vec.fit_on_texts(df['tokens'])
l=len(vec.word_index)
print(l)
print((list(vec.word_index))[:10])

8490
['a', '<start>', '<end>', 'in', 'the', 'on', 'is', 'and', 'dog', 'with']


In [70]:
#Here we are generating a matrix that contains embedding of each word in our vocabulary
r=0
M=(np.zeros((l,300)))
d=pd.DataFrame()
for el in vec.word_index:
  try:
    M[r,:]=word2vec[str(el)]#put entire word vector for el in rth row
  except:
    M[r,:]=np.zeros((1,300)) #in case of an unknown word, simply put zero vector
    #print('error for ',' ',el)
  d=d.append(pd.DataFrame(data={'row':[r], 'word': [el]}))# storing the mapping of row to word
  r=r+1

In [71]:
M.shape


(8490, 300)

In [72]:
#pad token '_' has been dealt seperately because it might have affected the word2vec training if used earlier
vec.word_index['_'] = 0 #adding 0 for padding
vec.index_word[0] = '_'
M = np.vstack((np.zeros((1,300)),M)) #putting zero vector at 0th row for padding
seq = vec.texts_to_sequences(df['tokens_pad']) #converting tokens to corrosponding indicies so that they can be
                                               #they can be used for mapping by embedding layer during training
seq_vec = np.array(seq).astype('int32')

In [73]:
df.head()

image  \
0  1000268201_693b08cb0e.jpg   
1  1000268201_693b08cb0e.jpg   
2  1000268201_693b08cb0e.jpg   
3  1000268201_693b08cb0e.jpg   
4  1000268201_693b08cb0e.jpg   

                                             caption  \
0  <start> A child in a pink dress is climbing up...   
1  <start> A girl going into a wooden building . ...   
2  <start> A little girl climbing into a wooden p...   
3  <start> A little girl climbing the stairs to h...   
4  <start> A little girl in a pink dress going in...   

                                              tokens  \
0  [<start>, A, child, in, a, pink, dress, is, cl...   
1  [<start>, A, girl, going, into, a, wooden, bui...   
2  [<start>, A, little, girl, climbing, into, a, ...   
3  [<start>, A, little, girl, climbing, the, stai...   
4  [<start>, A, little, girl, in, a, pink, dress,...   

                                          tokens_pad  
0  [<start>, A, child, in, a, pink, dress, is, cl...  
1  [<start>, A, girl, going, into, a, wooden, bui...  
2  [<start>, A, little, girl, climbing, into, a, ...  
3  [<start>, A, little, girl, climbing, the, stai...  
4  [<start>, A, little, girl, in, a, pink, dress,...

In [78]:
df.tokens_pad[0]

['<start>',
 'A',
 'child',
 'in',
 'a',
 'pink',
 'dress',
 'is',
 'climbing',
 'up',
 'a',
 'set',
 'of',
 'stairs',
 'in',
 'an',
 'entry',
 'way',
 '<end>',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_']

In [85]:
# print(M) ,
print(seq_vec)

[[ 2  1 43 ...  0  0  0]
 [ 2  1 19 ...  0  0  0]
 [ 2  1 40 ...  0  0  0]
 ...
 [ 2  1 44 ...  0  0  0]
 [ 2  1 85 ...  0  0  0]
 [ 2  1 85 ...  0  0  0]]


In [93]:
list((vec.word_index).items())[:10]

[('a', 1),
 ('<start>', 2),
 ('<end>', 3),
 ('in', 4),
 ('the', 5),
 ('on', 6),
 ('is', 7),
 ('and', 8),
 ('dog', 9),
 ('with', 10)]

In [94]:
df.to_csv(r'/content/drive/MyDrive/deep_learning_projects/Image_captioning/data/captions_pros.csv',index=None,header=True) # all further mappings will be as per this csv
np.save('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/embedB.npy',M)
np.save('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/caption_vec.npy',seq_vec)

with open('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/word_ind_map.pkl', 'wb') as f:
  pickle.dump(vec.word_index, f, pickle.HIGHEST_PROTOCOL)

with open('/content/drive/MyDrive/deep_learning_projects/Image_captioning/Models_/ind_word_map.pkl', 'wb') as f:
  pickle.dump(vec.index_word, f, pickle.HIGHEST_PROTOCOL)